name: Build PS5 Camera Service

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.16"

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Copy artifacts to build folder
        run: |
          mkdir build/release-package
          copy "build/Release/PS5CameraService.exe" "build/release-package/"
          copy "build/Release/PS5CameraLoader.exe" "build/release-package/"
          copy "firmware_discord_and_gamma_fix.bin" "build/release-package/"

      - name: Create installer script
        run: |
          echo @echo off > build/release-package/install.bat
          echo echo Installing PS5 Camera Auto-Loader Service... >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Check for admin rights >> build/release-package/install.bat
          echo net session ^>nul 2^>^&1 >> build/release-package/install.bat
          echo if %%errorLevel%% == 0 ( >> build/release-package/install.bat
          echo     echo Administrative privileges confirmed. >> build/release-package/install.bat
          echo ^) else ( >> build/release-package/install.bat
          echo     echo This installer requires administrative privileges. >> build/release-package/install.bat
          echo     echo Please run as administrator. >> build/release-package/install.bat
          echo     pause >> build/release-package/install.bat
          echo     exit /b 1 >> build/release-package/install.bat
          echo ^) >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Stop existing service if running >> build/release-package/install.bat
          echo sc stop PS5CameraService ^>nul 2^>^&1 >> build/release-package/install.bat
          echo sc delete PS5CameraService ^>nul 2^>^&1 >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Create service directory >> build/release-package/install.bat
          echo mkdir "%%PROGRAMFILES%%\PS5CameraService" 2^>nul >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Copy service files >> build/release-package/install.bat
          echo copy "PS5CameraService.exe" "%%PROGRAMFILES%%\PS5CameraService\" >> build/release-package/install.bat
          echo copy "firmware_discord_and_gamma_fix.bin" "%%PROGRAMFILES%%\PS5CameraService\" >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Install Windows Service >> build/release-package/install.bat
          echo sc create PS5CameraService binPath= "\"%%PROGRAMFILES%%\PS5CameraService\PS5CameraService.exe\"" start= auto DisplayName= "PS5 Camera Auto-Loader" >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo REM Start service >> build/release-package/install.bat
          echo sc start PS5CameraService >> build/release-package/install.bat
          echo. >> build/release-package/install.bat
          echo echo. >> build/release-package/install.bat
          echo echo Service installed and started successfully! >> build/release-package/install.bat
          echo echo PS5 Camera will now automatically load firmware when connected. >> build/release-package/install.bat
          echo echo. >> build/release-package/install.bat
          echo echo To uninstall: >> build/release-package/install.bat
          echo echo   sc stop PS5CameraService >> build/release-package/install.bat
          echo echo   sc delete PS5CameraService >> build/release-package/install.bat
          echo echo   rmdir /s "%%PROGRAMFILES%%\PS5CameraService" >> build/release-package/install.bat
          echo pause >> build/release-package/install.bat

      - name: Create uninstaller script
        run: |
          echo @echo off > build/release-package/uninstall.bat
          echo echo Uninstalling PS5 Camera Auto-Loader Service... >> build/release-package/uninstall.bat
          echo. >> build/release-package/uninstall.bat
          echo REM Check for admin rights >> build/release-package/uninstall.bat
          echo net session ^>nul 2^>^&1 >> build/release-package/uninstall.bat
          echo if %%errorLevel%% == 0 ( >> build/release-package/uninstall.bat
          echo     echo Administrative privileges confirmed. >> build/release-package/uninstall.bat
          echo ^) else ( >> build/release-package/uninstall.bat
          echo     echo This uninstaller requires administrative privileges. >> build/release-package/uninstall.bat
          echo     echo Please run as administrator. >> build/release-package/uninstall.bat
          echo     pause >> build/release-package/uninstall.bat
          echo     exit /b 1 >> build/release-package/uninstall.bat
          echo ^) >> build/release-package/uninstall.bat
          echo. >> build/release-package/uninstall.bat
          echo REM Stop and delete service >> build/release-package/uninstall.bat
          echo sc stop PS5CameraService >> build/release-package/uninstall.bat
          echo sc delete PS5CameraService >> build/release-package/uninstall.bat
          echo. >> build/release-package/uninstall.bat
          echo REM Remove service directory >> build/release-package/uninstall.bat
          echo rmdir /s /q "%%PROGRAMFILES%%\PS5CameraService" >> build/release-package/uninstall.bat
          echo. >> build/release-package/uninstall.bat
          echo echo Service uninstalled successfully! >> build/release-package/uninstall.bat
          echo pause >> build/release-package/uninstall.bat

      - name: Create README
        run: |
          echo # PS5 Camera Auto-Loader Service > build/release-package/README.md
          echo. >> build/release-package/README.md
          echo This service automatically loads firmware to PS5 cameras when connected to Windows. >> build/release-package/README.md
          echo. >> build/release-package/README.md
          echo ## Installation >> build/release-package/README.md
          echo 1. Right-click `install.bat` and select "Run as administrator" >> build/release-package/README.md
          echo 2. The service will be installed and started automatically >> build/release-package/README.md
          echo. >> build/release-package/README.md
          echo ## Usage >> build/release-package/README.md
          echo - Simply connect your PS5 camera to USB >> build/release-package/README.md
          echo - The firmware will be uploaded automatically >> build/release-package/README.md
          echo - No user interaction required >> build/release-package/README.md
          echo. >> build/release-package/README.md
          echo ## Uninstallation >> build/release-package/README.md
          echo - Right-click `uninstall.bat` and select "Run as administrator" >> build/release-package/README.md
          echo. >> build/release-package/README.md
          echo ## Testing >> build/release-package/README.md
          echo - Use `PS5CameraLoader.exe` to manually test firmware loading >> build/release-package/README.md
          echo - Use `PS5CameraService.exe --console` to test service in console mode >> build/release-package/README.md

      - name: List build artifacts
        run: dir build/release-package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PS5CameraService-Windows
          path: |
            build/release-package/PS5CameraService.exe
            build/release-package/PS5CameraLoader.exe
            build/release-package/firmware_discord_and_gamma_fix.bin
            build/release-package/install.bat
            build/release-package/uninstall.bat
            build/release-package/README.md

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/release-package/PS5CameraService.exe
            build/release-package/PS5CameraLoader.exe
            build/release-package/firmware_discord_and_gamma_fix.bin
            build/release-package/install.bat
            build/release-package/uninstall.bat
            build/release-package/README.md
          body: |
            ## PS5 Camera Auto-Loader Service

            Automatically loads firmware to PS5 cameras when connected to Windows.

            ### Installation
            1. Download all files
            2. Right-click `install.bat` and select "Run as administrator"
            3. Connect your PS5 camera - firmware will load automatically

            ### Files
            - `PS5CameraService.exe` - Windows Service executable
            - `PS5CameraLoader.exe` - Manual firmware loader (for testing)
            - `firmware_discord_and_gamma_fix.bin` - PS5 camera firmware
            - `install.bat` - Service installer script
            - `uninstall.bat` - Service uninstaller script
            - `README.md` - Documentation
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
